server:
  port: 8099
  servlet:
    context-path: /NeedManagement

spring:
  mvc:
    pathmatch:
      # 配置策略 如sping版本高于2.4以上则需要添加，否则会导致swagger文档不适配
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:dm://28.9.125.1:5236/DBHTXDKZ
    username: DBHTXDKZ
    password: 123456789
    driver-class-name: dm.jdbc.driver.DmDriver




